### ISSUE TITLE
plot_roc_curve uses hardcoded column names

### ISSUE THREAD

**Issue by KPLauritzen** [dfds-data/dfds-ds-toolbox#11]
https://github.com/dfds-data/dfds-ds-toolbox/blob/c97f6e9ffd8a31e43fef84748cbc287431ab8448/dfds_ds_toolbox/analysis/plotting.py#L199

We should either take arrays as inputs or take column names as input instead. 
I would rather standardize on the `y_true, y_pred` idiom. We use that other places.

**Comment by dingobar** [comment]
Maybe [this type](https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike) can be used, ie. just accept anything that is accepted by `np.array` (`List`, `pd.Series` etc.)?

**Comment by KPLauritzen** [comment]
> Maybe [this type](https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike) can be used, ie. just accept anything that is accepted by `np.array` (`List`, `pd.Series` etc.)?

I have used `Sequence[int]` and `Sequence[float]` instead. That lets me specify a dtype. 
See https://docs.python.org/3/library/typing.html#typing.Sequence

**Comment by dingobar** [comment]
> > Maybe [this type](https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike) can be used, ie. just accept anything that is accepted by `np.array` (`List`, `pd.Series` etc.)?
> 
> I have used `Sequence[int]` and `Sequence[float]` instead. That lets me specify a dtype. 
> See https://docs.python.org/3/library/typing.html#typing.Sequence

Not sure if I know the consequences of one or the other but using a built in is probably better!
