### ISSUE TITLE
We are not measuring code coverage

### ISSUE THREAD

**Issue by KPLauritzen** [dfds-data/dfds-ds-toolbox#18]
In Azure DevOps we could export code coverage reports and get an overview from the pull request. Can we do the same here?

**Comment by dingobar** [comment]
It would be nice if we could make a code coverage check in the pr pipeline and then
1)  Fail the pipeline if coverage is below a threshold
2) Publish the results as a comment in the PR automatically

Found these GH actions tasks we could consider using:
https://github.com/marketplace/actions/pytest-coverage-commentator
https://github.com/marketplace/actions/pytester-cov

**Comment by KPLauritzen** [comment]
There is also https://about.codecov.io/
I used it on an old project https://github.com/moneyball-dk/moneyball_app, but I can't remember how that went

**Comment by KPLauritzen** [comment]
I've tested pytester-cov [here](https://github.com/dfds-data/dfds-ds-toolbox/pull/20). 
It seems good to me.

**Comment by KPLauritzen** [comment]
Closed by #20
