### ISSUE TITLE
Remove model_selection sub package

### ISSUE THREAD

**Issue by nybyhansen** [dfds-data/dfds-ds-toolbox#23]
Should we remove the `model_selection` sub-package? We have to classes that I really can't see what is doing that relates to selecting models. Link: 
[dfds_ds_toolbox/model_selection/model_selection.py](https://github.com/dfds-data/dfds-ds-toolbox/blob/79dc63f238c542af3ab65677871f0e756ad0a14c/dfds_ds_toolbox/model_selection/model_selection.py)

I might be tired but it looks like just a wrapper of an estimator 😄

**Comment by KPLauritzen** [comment]
There is an example where it is used [in the docs](https://dfds-ds-toolbox.readthedocs.io/en/stable/usage.html#model-selection).

I don't think this is easily available in standard scikit-learn, but there might be a cleaner implementation in some other library?

**Comment by KPLauritzen** [comment]
This is similar to what @pacanada and I saw in a project recently. I would rather have this semi-standardized implementation than something ad-hoc inside the project. 
On the other hand, I don't think this is something that we should encourage people to do. Choosing different models inside the pipeline really obfuscates what is going on if it is ever put into production. 

Pinging @dingobar @kaqmak for thoughts on this.
