### ISSUE TITLE
Remove rich as a dependency?

### ISSUE THREAD

**Issue by KPLauritzen** [dfds-data/dfds-ds-toolbox#24]
I think I have changed my mind on having `rich` as a dependency. 
Can we get by with just standard library logging instead? 
I think we should stick to dependencies that are clearly needed: `matplotlib`, `pandas`, etc.

That makes it more managable to have installed in most projects. 
ping @dingobar @dfds-data/data-science-chapter

**Comment by pacanada** [comment]
Makes sense I guess. But if we remove the rich handler we do not have coloured log messages anymore, what brings the question: which extra functionality the logging module is providing. Is/was it only the coloured messages, the logging file? If no rich handler is used the task of initialize the logger is not so complex anymore and maybe it does not makes sense to have a module just for that

**Comment by KPLauritzen** [comment]
We are worried that logging with rich will look weird in eg k8s logs. As a test we will try logging with rich from inside a docker container. If that looks weird, it will also look weird in k8s

**Comment by nybyhansen** [comment]
I think it makes sense to remove it and implement it on a project-to-project basis for local development.

**Comment by KPLauritzen** [comment]
I think it makes sense to have an init_logger function in here. I hate having to look up the "logging cookbook" any time I want to start using logging library instead of print

**Comment by pacanada** [comment]
I also find it useful. I am using it for some projects and I prefer not to implement it individually, so I would keep it. If any project has special needs in terms of logging I guess you can then implement a custom one. 

However, i think we should address the truncating behaviour of the rich handler when running it in docker or k8

**Comment by dingobar** [comment]
I personally never saw the need to beautify logs, but if the consensus is that it is useful then I'll happily concede.

> However, i think we should address the truncating behaviour of the rich handler when running it in docker or k8

Yes, in production the containers should definitely just write a single line per `logger` call. I'd consider this a bug to be honest.
