### ISSUE TITLE
We are duplicating functionality from sklearn

### ISSUE THREAD

**Issue by KPLauritzen** [dfds-data/dfds-ds-toolbox#8]
https://github.com/dfds-data/dfds-ds-toolbox/blob/eed550130636cd1c42921408e7fcfcd78fe9258f/dfds_ds_toolbox/feature_selection/feat_selector.py#L15

The feature selector here seems to be the same as the  [sequential feature selector](https://scikit-learn.org/stable/modules/feature_selection.html#sequential-feature-selection) in scikit learn. 

I dont see a reason to keep maintaining something that is duplicated in a place like scikit learn.

**Comment by dingobar** [comment]
I suggest logging a deprecation warning and deprecating in 0.9.0

**Comment by KPLauritzen** [comment]
> I suggest logging a deprecation warning and deprecating in 0.9.0

Yeah, seems like a good way of handling it.

**Comment by KPLauritzen** [comment]
Added a draft PR. I think we can deprecate this whole module. It is all covered in `sklearn.model_selection`.
